services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile  # Custom Dockerfile for Jenkins
    container_name: jenkins
    ports:
      - "8010:8080"   # Jenkins web UI
      - "50000:50000" # Jenkins agent
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    networks:
      - ci_net
    environment:
      - JENKINS_OPTS=--httpPort=8080

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"  # SonarQube web UI
    networks:
      - ci_net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:7.49.6
    container_name: artifactory
    restart: always
    networks:
      - ci_net
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - artifactory:/var/opt/jfrog/artifactory

volumes:
  artifactory:
  jenkins_home:
networks:
  ci_net:
    driver: bridge